version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: build

  clean:
    cmds:
      - rm -Rf dist

  build:
    cmds:
      - pnpm exec tsc

  run:
    cmds:
      - task: default
      - pnpm exec tsx export.ts
